#Should mod be enabled?
enableMod = true
#Should show bar in HUD?
showBar = true
#Should show entity name?
showEntityName = true
#Should show entity health?
showHealth = true
#Should show entity armor?
showArmor = true
#Should show bosses?
showBosses = false

[hud]
	#Range: > 0
	distance = 60
	#Range: -Infinity ~ Infinity
	xValue = 4.0
	#Range: -Infinity ~ Infinity
	yValue = 4.0
	#Range: 0.0 ~ Infinity
	scale = 1.0
	#Range: > 0
	hideDelay = 5
	#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
	position = "TOP_LEFT"

[colors]
	#Default Value: 00ff00
	passiveColor = "00ff00"
	#Default Value: 008000
	passiveColorSecondary = "008000"
	#Default Value: ff0000
	hostileColor = "ff0000"
	#Default Value: 800000
	hostileColorSecondary = "800000"
	#Default Value: 0000ff
	neutralColor = "0000ff"
	#Default Value: 000080
	neutralColorSecondary = "000080"

